services:
  api:
    environment:
      APP_ENV: production
  nginx:
    ports: !override ["80:80", "443:443"]
    volumes:
      - ./deploy/nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deploy/certs:/etc/nginx/certs:ro
